name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # Adjust the Node.js version as needed

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn' # or 'npm' if you're using npm

      - name: Change to App Directory
        run: cd app

      - name: Install Dependencies
        run: yarn install
        working-directory: ./app

      - name: Build
        run: yarn build
        working-directory: ./app

      - name: Run Tests
        run: yarn test
        working-directory: ./app

    # Add any additional steps as needed
